// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:card_stash/models/card.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(BarcodeTypeAdapter());
    registerAdapter(LoyaltyCardAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(BarcodeTypeAdapter());
    registerAdapter(LoyaltyCardAdapter());
  }
}
